name: Manylinux

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  deploy:
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.7]
        rust-version: [stable]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Set up Rust ${{ matrix.rust-version }}
      uses: hecrj/setup-rust-action@v1
      with:
        rust-version: ${{ matrix.rust-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install twine
    - name: Build source distribution
      run: |
        python setup.py sdist
    - name: Build binary distributions
      env:
        DOCKER_IMAGE: quay.io/pypa/manylinux1_x86_64
        PLAT: manylinux1_x86_64
        PYVER: cp37-cp37m
      run: |
        docker pull $DOCKER_IMAGE
        docker run --rm -e PLAT=$PLAT -e PYVER=$PYVER -v `pwd`:/io $DOCKER_IMAGE /io/build-manylinux-wheels.sh
    - name: Publish wheels to PyPI
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        twine upload wheelhouse/svinst*-manylinux*.whl
        twine upload dist/*
